config/routes.rb
Rails.application.routes.draw do
  resources :comments, :except => :index do
    post :preview, :on => :collection
  end

  namespace :admin do
    resources :comments
  end
end

app/models/comment.rb
require 'validates_email_format_of'

class Comment < ActiveRecord::Base
  class CommentNotAllowed < StandardError; end

  def self.approved
    where :approved => true
  end

  def self.unapproved
    where :approved => false
  end

  after_save do
    commentable.touch
  end


  belongs_to :site
  belongs_to :section
  belongs_to :commentable, :polymorphic => true
  # make sure we're storing the base clase for STI
  def commentable_type=(sType)
    super(sType.to_s.classify.constantize.base_class.to_s)
  end
  has_many :activities, :as => :object

  composed_of :author, :class_name => "User", :mapping => [ %w(author_name name), %w(author_email email) ]

  validates_presence_of :body, :commentable, :author_name, :author_email
  validates_email_format_of :author_email

  before_validation :set_owners
  before_create :authorize_commenting

  def owner
    commentable
  end

  def filter
    commentable.comment_filter
  end

  def author_link
    name = author_name.presence || (respond_to?(:author) && author.respond_to?(:name) ? author.name : nil)
    return name unless author_homepage.present?
    %(<a href="#{author_homepage}">#{name}</a>).html_safe
  end

  def unapproved?
    !approved?
  end

  define_model_callbacks :approve, :unapprove

  protected

  def authorize_commenting
    if commentable && !commentable.accept_comments?
      raise CommentNotAllowed, I18n.t(:'adva.comments.messages.not_allowed')
    end
  end

  def set_owners
    if commentable # TODO in what cases would commentable be nil here?
      self.site = commentable.site
      self.section = commentable.section
    end
  end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < Admin::BaseController
  layout "admin"

  before_action :set_comment, :only => [:edit, :update, :destroy]

  def index
    # FIXME how to remove the Topic dependency here? 
    # maybe make Comment a subclass of Comment::Base or something so that we can use STI to exclude 
    # special comment types?
    @comments = @site.comments.where(['commentable_type NOT IN (?)', 'Topic']).
      reorder("comments.created_at DESC").
      paginate(:page => current_page, :per_page => 25)
  end

  def edit
  end

  def update
    if @comment.update comment_params
      trigger_events @comment
      flash[:notice] = t(:'adva.comments.flash.update.success')
      redirect_to params[:return_to] || admin_comments_url
    else
      flash.now[:error] = t(:'adva.comments.flash.update.failure')
      render :action => :edit
    end
  end

  def destroy
    @comment.destroy
    trigger_events @comment
    flash[:notice] = t(:'adva.comments.flash.destroy.success')
    redirect_to params[:return_to] || admin_comments_url
  end

  private

  def set_menu
    @menu = Menus::Admin::Comments.new
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end
  
  def current_resource
    @comment ? @comment.commentable : @content || @section || @site
  end

  def comment_params
    params.require(:comment).permit(:body, :approved)
  end
end

app/controllers/comments_controller.rb
class CommentsController < BaseController
  # TODO apparently it is not possible to use protect_from_forgery with
  # page cached forms? is that correct? as protect_from_forgery seems to
  # validate the form token against the session and ideally when all pages
  # and assets are cached there is no session at all this seems to make sense.
  #
  # Rails docs say: "done by embedding a token based on the session ... in all
  # forms and Ajax requests generated by Rails and then verifying the authenticity
  # of that token in the controller"
  # http://api.rubyonrails.org/classes/ActionController/RequestForgeryProtection/ClassMethods.html
  #
  # Note: Could fetch forgery token via AJAX?

  protect_from_forgery :except => [:preview, :create]

  layout 'default'

  before_action :set_section
  before_action :set_comment, :only => [:show, :update, :destroy]
  # Ensure @commentable is available for update to support param merging and filters
  before_action :set_commentable, :only => [:show, :preview, :create, :update]

  invisible_captcha only: [:create, :update], honeypot: :subtitle, if: -> { current_user.anonymous? }

  def show
  end

  def preview
    @comment = @commentable.comments.build(comment_params)
    @comment.send(:process_filters)
    render :layout => false
  end

  def create
    @comment = @commentable.comments.build(comment_params)
    if @comment.save
      trigger_events @comment
      CommentMailer.comment_notification(@comment).deliver_later
      if current_user.anonymous?
        flash.notice = "Your comment is being reviewed, and will be posted shortly. Thank you for commenting!"
      else
        @comment.update_column :approved, true
        flash.notice = "You're an admin, so your comment is being posted immediately! Refresh the page to see it."
      end
      respond_to do |format|
        format.html { redirect_to "#{request.env['HTTP_REFERER']}#comments" }
        format.js { render json: true }
      end
    else
      flash[:error] = @comment.errors.full_messages.to_sentence # TODO hu.
      respond_to do |format|
        format.html { redirect_to "#{request.env['HTTP_REFERER']}#comments" }
        format.js { render json: false }
      end
    end
  end

  def update
    if @comment.update(comment_params)
      trigger_events(@comment)
      flash.notice = t(:'adva.comments.flash.update.success')
      render json: true
    else
      set_commentable
      flash[:error] = @comment.errors.full_messages.to_sentence
      render json: false
    end
  end

  def destroy
    @comment.destroy
    trigger_events @comment
    redirect_to "/", notice: t(:'adva.comments.flash.destroy.success')
  end

  protected

  def comment_params
    params.require(:comment).permit(
      :author_email,
      :author_name,
      :body,
      :commentable_id,
      :commentable_type,
    ).merge(site_id: @commentable.site_id, section_id: @commentable.section_id)
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def set_commentable
    @commentable = if @comment
      @comment.commentable or raise ActiveRecord::RecordNotFound
    else
      begin
        klass = params.dig(:comment, :commentable_type).constantize
        raise NameError unless klass.has_many_comments?
      rescue NameError
        raise ActiveRecord::RecordNotFound
      end
      klass.find(params.dig(:comment, :commentable_id))
    end
  end

  def current_resource
    @comment || @commentable
  end
end

app/helpers/admin/comments_helper.rb
module Admin
  module CommentsHelper
    def comment_expiration_options
      I18n.with_options :scope => :'adva.comments.options.expiration' do |i18n|
        [ [i18n.t(:not_allowed),                           -1 ],
          [i18n.t(:never_expire),                           0 ],
          [i18n.t(:x_hours_after_publishing, :count => 24), 1 ],
          [i18n.t(:x_weeks_after_publishing, :count => 1),  7 ],
          [i18n.t(:x_months_after_publishing, :count => 1), 30],
          [i18n.t(:x_months_after_publishing, :count => 3), 90] ]
      end
    end

    def comments_state_options
      [
        ['Approved', 'approved'],
        ['Unapproved', 'unapproved']
      ]
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def comments_feed_title(*owners)
    options = owners.extract_options!
    separator = options[:separator] || ' &raquo; '
    'Comments: ' + owners.compact.uniq.map(&:title).join(separator)
  end

  methods = %w(admin_comments_path admin_comment_path
               new_admin_comment_path edit_admin_comment_path)

  methods.each do |method|
    module_eval <<-CODE, __FILE__, __LINE__
      def #{method}(*args)
        options = args.extract_options!
        merge_admin_comments_query_params(options)
        super *(args << options).compact
      end
    CODE
  end

  def link_to_content_comments_count(content, options = {:total => true})
    total = content.comments_count
    approved = content.approved_comments_count
    return options[:alt] || "None" if approved == 0
    text = if total == approved or !options[:total]
      "#{approved.to_s.rjust(2, '0')}"
    else
      "#{approved.to_s.rjust(2, '0')} (#{total.to_s.rjust(2, '0')})"
    end
    link_to_content_comments(text, content)
  end

  def link_to_content_comments(*args)
    options = args.extract_options!
    text = args.shift if args.first.is_a?(String) || args.first.is_a?(Symbol)
    content, comment = *args
    return unless content.approved_comments_count > 0 || content.accept_comments?

    text = t(text) if text.is_a?(Symbol)
    text ||= pluralize(content.approved_comments_count, "comment")
    options.merge! :anchor => (comment ? dom_id(comment) : 'comments')
    link_to text, [content.section, content], options
  end

  def link_to_content_comment(*args)
    options = args.extract_options!
    args.insert(args.size - 1, args.last.commentable)
    link_to_content_comments(*args << options)
  end

  def link_to_remote_comment_preview
    link_to("Preview", preview_comments_path, :id => 'preview_comment', :style => "display:none;") +
      image_tag('adva_cms/indicator.gif', :alt => '', :id => 'comment_preview_spinner', :style => 'display:none;')
  end

  def comment_form_hidden_fields(commentable)
    hidden_field_tag('return_to', request.fullpath) + "\n" +
    hidden_field_tag('comment[commentable_type]', commentable.class.name, :id => 'comment_commentable_type') + "\n" +
    hidden_field_tag('comment[commentable_id]', commentable.id, :id => 'comment_commentable_id') + "\n"
  end

  private

    # TODO obviously doesn't work as expected on the SectionsController where the
    # section_id is in params[:id]
    def merge_admin_comments_query_params(options)
      options.merge! params.slice(:section_id, :content_id).reject{|key, value| value.blank? }.to_unsafe_hash
      options.symbolize_keys!
      options.delete(:section_id) if options[:content_id]
    end
end

app/views/comments/_comment.html.erb
<li id="<%= dom_id(comment) %>" class="<%= cycle 'alt', '' %> clearing">
  <div class="meta">
    <p><%= link_to_author(comment) %></p>
    <p><%= datetime_with_microformat(comment.created_at, :format => :long) %></p>
    <% unless comment.approved? %>
      <p><%= t(:'adva.comments.info.under_review') %></p>
    <% end  %>
  </div>
  <div class="comment">
    <%= comment.body_html %>
    <a href="#<%= dom_id(comment) %>" title="" style="display:none;">#</a>
  </div>
</li>

app/views/comments/_form.html.erb
<%# @comment ||= commentable.comments.build %>
<% if @comment %>
	<% authorized_tag(:div, :create, @comment, :id => 'comment_form_wrapper') do %>
    <div id="registered_author" style="display: none;">
      <p><%= t(:'adva.info.greeting_logged_in') %></p>
    </div>

    <h2><%= @comment.new_record? ? t(:'adva.comments.titles.add_reply') : t(:'adva.comments.titles.edit') %></h2>

    <%= form_for :comment, @comment, :url => (@comment.new_record? ? comments_path : comment_path(@comment)), :html => { :id => 'comment_form', :method => (@comment.new_record? ? :post : :put) } do |f| -%>
      <%= invisible_captcha :homepage, :comment %>
      <%= comment_form_hidden_fields commentable %>

      <%= fields_for @comment.author do |author| %>
        <div id="anonymous_author">
          <p>
            <%= author.label :name, 'Name' %>
            <%= author.text_field :name %>
          </p>
          <p> 
            <%= author.label :email, 'E-Mail' %>
            <%= author.email_field :email %>
          </p>
          <p> 
            <%= author.label :homepage %>
            <%= author.text_field :homepage %>
          </p>
        </div>
      <% end %>

      <p>
        <%= f.text_area :body %>
      </p>

      <p id="preview"></p>

      <p>
        <input type="text" name="comment[url]" style="background-color: transparent; border: 0px" />
        <%= submit_tag (@comment.new_record? ? t(:'adva.comments.titles.submit_comment') : t(:'adva.comments.titles.save_comment')) %>
        <%= link_to_remote_comment_preview %>
      </p>
    <% end %>
	<% end %>
<% end %>

app/views/comments/_list.html.erb
<% if comments.present? %>
  <div id="comments">
    <h2><%= t(:'adva.comments.titles.comment_with_count', :count => comments.size) %></h2>
    <ol>
      <%= render :partial => 'comments/comment', :collection => comments %>
    </ol>
  </div>
<% end %>

app/views/comments/preview.html.erb
<div id="comment_preview">
  <%= @comment.body_html %>
</div>

app/views/comments/show.html.erb
<div id="comments">
  <h2><%= t(:'adva.comments.titles.comment_number', :number => @comment.id) %></h2>
  <p>
		<%= t(:'adva.comments.labels.on') %>: <%= link_to_content @comment.commentable %>
	</p>
  <ol>
    <%= render :partial => 'comments/comment', :object => @comment %>
  </ol>
</div>
<% if !@comment.approved? && current_user.admin? %>
  <%= render :partial => 'comments/form', :locals => { :commentable => @comment.commentable }  %>
<% end %>